{{- if and (not .Values.mysql.existingSecret) .Values.mysql.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "inventory.fullname" . }}-mysql-secret
  labels:
    {{- include "inventory.labels" . | indent 4 }}
type: Opaque
data:
  mysql-password: {{ .Values.mysql.password | b64enc | quote }}
{{- end }}