replicaCount: 1

image:
  repository: ibmcase/bluecompute-inventory
  tag: 0.6.0
  pullPolicy: Always

service:
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080
  managementPort: 8090
  nodePort: 32380

ingress:
  enabled: false
  hostname: #inventory.bluecompute.com
  path: /micro/inventory
  annotations:
    ingress.bluemix.net/redirect-to-https: "True"
  enableTLS: false
  TLS:
  - secretName: inventory.bluecompute.com
    hosts:
      - inventory.bluecompute.com

mysql:
  host: inventory-mysql
  port: 3306
  existingSecret:
  user: dbuser
  password: password
  database: inventorydb
  # For mysql init container
  image: "mysql"
  imageTag: "5.7.14"
  imagePullPolicy: IfNotPresent
  istio:
    mTLS: ISTIO_MUTUAL
    loadBalancer: LEAST_CONN

resources:
  limits:
    memory: 384Mi
  requests:
    memory: 64Mi

labels:
  app: inventory
  version: v1
  tier: backend

securityContext:
  runAsUser: 2000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

istio:
  enabled: false
  # ISTIO_MUTUAL, SIMPLE, DISABLE
  mTLS: ISTIO_MUTUAL
  # LEAST_CONN, ROUND_ROBIN
  loadBalancer: LEAST_CONN
  gateway:
    enabled: false
    name:
    hosts:
      - "inventory.bluecompute.com"
    TLS:
      enabled: false
      # SIMPLE, MUTUAL
      mode: SIMPLE
      httpsRedirect: false
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      caCertificates: /etc/istio/ingressgateway-ca-certs/ca-chain.cert.pem

global:
  istio:
    enabled:
    gateway:
      name: